apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamcs
  labels:
    app: yamcs
  namespace: mission-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yamcs
  template:
    metadata:
      labels:
        app: yamcs
    spec:
      containers:
      - name: yamcs
        image: quay.io/rhnspdev/ssconf-yamcs:v1.0
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: yamcs
spec:
  selector:
    app: yamcs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090