name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['yamcs', 'openmct', 'couchdb', 'simulator', 'apache']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.directory }}
        file: ./${{ matrix.directory }}/Dockerfile
        push: true
        tags: quay.io/rhnspdev/${{ matrix.directory }}:latest